ITL_MakeId.Web/Controllers/CardsController.cs
using ITL_MakeId.Data;
using ITL_MakeId.Model.DomainModel;
using ITL_MakeId.Model.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ExcelDataReader;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

using System.Data.OleDb;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Http;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace ITL_MakeId.Web.Controllers
{
    [Authorize]
    public class CardsController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IConfiguration _configuration;
        private string filePath;
        private string filePathSignature;

        public CardsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, IConfiguration configuration)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _configuration = configuration;
        }


        public async Task<IActionResult> Dashboard()
        {
            ViewBag.RequestedIdentityCards = _context.IdentityCards.Where(c => c.ValidationEndDate == null)
                .Include(c => c.BloodGroup)
                .Include(c => c.Designation).Count();


            ViewBag.ValidatedIdentityCards = _context.IdentityCards.Where(c => c.ValidationEndDate >= DateTime.Now)
                .Include(c => c.BloodGroup)
                .Include(c => c.Designation).Count();

            ViewBag.ExpiredIdentityCards = _context.IdentityCards.Where(c => c.ValidationEndDate < DateTime.Now)
                .Include(c => c.BloodGroup)
                .Include(c => c.Designation).Count();


            return View();
        }


        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var identityCards = await _context.IdentityCards
                .Include(c => c.BloodGroup)
                .Include(c => c.Designation).ToListAsync();


            IdentityCardViewModel model = new IdentityCardViewModel
            {
                IdentityCards = identityCards
            };

            ViewBag.Message = TempData["Message"];
            return View(model);
        }


        public async Task<IActionResult> ValidatedUsers()
        {

            var identityCards = await _context.IdentityCards.Where(c => c.ValidationEndDate >= DateTime.Now)
                .Include(c => c.BloodGroup)
                .Include(c => c.Designation).ToListAsync();


            IdentityCardViewModel model = new IdentityCardViewModel();
            model.IdentityCards = identityCards;
            ViewBag.Title = "Validated Card Users";

            return View(model);
        }


        public async Task<IActionResult> ExpiredUserCards()
        {

            var identityCards = await _context.IdentityCards.Where(c => c.ValidationEndDate < DateTime.Now)
                .Include(c => c.BloodGroup)
                .Include(c => c.Designation).ToListAsync();


            IdentityCardViewModel model = new IdentityCardViewModel();
            model.IdentityCards = identityCards;
            ViewBag.Title = "Expired Card Users";

            return View("ValidatedUsers", model);
        }


        public async Task<IActionResult> UserRequestForCard()
        {

            var identityCards = await _context.IdentityCards.Where(c => c.ValidationEndDate == null)
                .Include(c => c.BloodGroup)
                .Include(c => c.Designation).ToListAsync();


            IdentityCardViewModel model = new IdentityCardViewModel();
            model.IdentityCards = identityCards;
            ViewBag.Title = "Users Requested For Card ";

            return View("ValidatedUsers", model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var identityCard = await _context.IdentityCards.Include(c => c.BloodGroup)
                .Include(c => c.Designation)
                .FirstOrDefaultAsync(m => m.Id == id);

            IdentityCardViewModel model = new IdentityCardViewModel();
            model.IdentityCard = identityCard;

            if (identityCard == null)
            {
                return NotFound();
            }

            return View(model);
        }


        public IActionResult CardRegistrationMenu()
        {
            return View();
        }


        public IActionResult Create()
        {
            IdentityCardViewModel model = new IdentityCardViewModel();
            ViewData["BloodGroups"] = new SelectList(_context.BloodGroups, "Id", "Name");
            ViewData["Designations"] = new SelectList(_context.Designations, "Id", "Title");
            ViewData["Departments"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["CardCategories"] = new SelectList(_context.CardCategories, "Id", "CategoryName");

            var identitycardInfo = _context.IdentityCards.ToList();
            var cardNumber = identitycardInfo.LastOrDefault()?.CardNumber;

            model.CardNumber = model.GetCardNumber(cardNumber);
            return View(model);
        }


        [Microsoft.AspNetCore.Mvc.HttpPost]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IdentityCardViewModel identityCardViewModel)
        {

            ViewData["BloodGroups"] = new SelectList(_context.BloodGroups, "Id", "Name");
            ViewData["Designations"] = new SelectList(_context.Designations, "Id", "Title");
            ViewData["Departments"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["CardCategories"] = new SelectList(_context.CardCategories, "Id", "CategoryName");

            if (identityCardViewModel.DateOfBirth > DateTime.Now)
            {
                ModelState.AddModelError("DateOfBirth", "Date of birth is not valid");
            }
            if (ModelState.IsValid)
            {
                //string uniqueFileName = null;
                //string uniqueFileNameSignature = null;
                //string uniqueFileNameAuthorizedSignature = null;
                //string uniqueFileNameCompanyLogo = null;
               
                //if (identityCardViewModel.ImagePathOfUser != null && identityCardViewModel.ImagePathOfUserSignature != null)
                //{
                //    string uplaodsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "image/user/");
                //    uniqueFileName = Guid.NewGuid().ToString() + "_" + identityCardViewModel.ImagePathOfUser.FileName;
                //    filePath = Path.Combine(uplaodsFolder, uniqueFileName);

                //    string uplaodsFolderSignature = Path.Combine(_webHostEnvironment.WebRootPath, "image/sig/");
                //    uniqueFileNameSignature = Guid.NewGuid().ToString() + "_" + identityCardViewModel.ImagePathOfUserSignature.FileName;
                //    filePathSignature = Path.Combine(uplaodsFolderSignature, uniqueFileNameSignature);

                //    string uplaodsFolderAuthSignature = Path.Combine(_webHostEnvironment.WebRootPath, "image/auth/");
                //    uniqueFileNameAuthorizedSignature = "9536f8a1-d3ad-41b6-8448-e748bb33f589_authsign.jpg";

                //    string uplaodsFolderLogo = Path.Combine(_webHostEnvironment.WebRootPath, "image/logo/");
                //    uniqueFileNameCompanyLogo = "68837796-1410-4966-a0bb-562e4b44c854_Logo.jpg";
                   

                //    using (var stream = new FileStream(filePath, FileMode.Create))
                //    {
                //        identityCardViewModel.ImagePathOfUser.CopyTo(stream);
                //    }

                //    using (var stream = new FileStream(filePathSignature, FileMode.Create))
                //    {
                //        identityCardViewModel.ImagePathOfUserSignature.CopyTo(stream);
                //    }

                //}

                identityCardViewModel.IdentityCard.Name = identityCardViewModel.Name;
                identityCardViewModel.IdentityCard.DesignationId = identityCardViewModel.DesignationId;
                identityCardViewModel.IdentityCard.Department = identityCardViewModel.Department;
                identityCardViewModel.IdentityCard.CardCategoryId = identityCardViewModel.CardCategoryId;
                identityCardViewModel.IdentityCard.BloodGroupId = identityCardViewModel.BloodGroupId;
                identityCardViewModel.IdentityCard.CardNumber = identityCardViewModel.CardNumber;
                identityCardViewModel.IdentityCard.DateOfBirth = identityCardViewModel.DateOfBirth;
                //identityCardViewModel.IdentityCard.ImagePathOfUser = uniqueFileName;
                //identityCardViewModel.IdentityCard.ImagePathOfUserSignature = uniqueFileNameSignature;
                //identityCardViewModel.IdentityCard.ImagePathOfAuthorizedSignature = uniqueFileNameAuthorizedSignature;
                //identityCardViewModel.IdentityCard.CompanyLogoPath = uniqueFileNameCompanyLogo;



                _context.Add(identityCardViewModel.IdentityCard);
                var saved = await _context.SaveChangesAsync();
                if (saved > 0)
                {
                    TempData["Message"] = "Saved Successfully";
                }
                return RedirectToAction(nameof(Index));
            }
            return View(identityCardViewModel);
        }



        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

ITL_MakeId.Web/Views/Cards/CardEdit.cshtml
@model ITL_MakeId.Model.ViewModel.IdentityCardViewModel

@{
    Layout = "_CardLayout";
    ViewData["Title"] = "Edit Card Information";
    var imageUrl = "/image/user/" + (Model.IdentityCard.ImagePathOfUser ?? "noimage.jpg");
}

<div class="col-md-6 mr-auto ml-auto p-0 mt-3 mb-5">
    <h3 class="formbar mb-0">Validity</h3>
    
    <div class="col-md-8">
        <div class="col-md-3">
            <img src="@imageUrl" class="upload-box border border-info" id="output" />
        </div>
    </div>


    <form asp-action="CardEdit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="IdentityCard.Id" />
        <div class="form-group">
            <label asp-for="CardCategoryId" class="control-label"></label>
            <select asp-for="CardCategoryId" class="form-control" asp-items="ViewBag.CardCategoryId"></select>
            <span asp-validation-for="CardCategoryId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DesignationId" class="control-label"></label>
            <select asp-for="DesignationId" class="form-control" asp-items="ViewBag.DesignationId"></select>
            <span asp-validation-for="DesignationId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Department" class="control-label"></label>
            <input asp-for="Department" class="form-control" />
            <span asp-validation-for="Department" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="BloodGroupId" class="control-label"></label>
            <select asp-for="BloodGroupId" class="form-control" asp-items="ViewBag.BloodGroupId"></select>
            <span asp-validation-for="BloodGroupId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CardNumber" class="control-label"></label>
            <input asp-for="CardNumber" class="form-control" />
            <span asp-validation-for="CardNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DateOfBirth" class="control-label"></label>
            <input asp-for="DateOfBirth" class="form-control" />
            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ImagePathOfUser" class="control-label"></label>
            <input asp-for="ImagePathOfUser" class="form-control" />
            <span asp-validation-for="ImagePathOfUser" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ImagePathOfUserSignature" class="control-label"></label>
            <input asp-for="ImagePathOfUserSignature" class="form-control" />
            <span asp-validation-for="ImagePathOfUserSignature" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ImagePathOfAuthorizedSignature" class="control-label"></label>
            <input asp-for="ImagePathOfAuthorizedSignature" class="form-control" />
            <span asp-validation-for="ImagePathOfAuthorizedSignature" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CompanyName" class="control-label"></label>
            <input asp-for="CompanyName" class="form-control" />
            <span asp-validation-for="CompanyName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CompanyAddress" class="control-label"></label>
            <input asp-for="CompanyAddress" class="form-control" />
            <span asp-validation-for="CompanyAddress" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CompanyLogoPath" class="control-label"></label>
            <input asp-for="CompanyLogoPath" class="form-control" />
            <span asp-validation-for="CompanyLogoPath" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CardInfo" class="control-label"></label>
            <input asp-for="CardInfo" class="form-control" />
            <span asp-validation-for="CardInfo" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ValidationStartDate" class="control-label"></label>
            <input asp-for="ValidationStartDate" class="form-control" />
            <span asp-validation-for="ValidationStartDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ValidationEndDate" class="control-label"></label>
            <input asp-for="ValidationEndDate" class="form-control" />
            <span asp-validation-for="ValidationEndDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="IssueDate" class="control-label"></label>
            <input asp-for="IssueDate" class="form-control" />
            <span asp-validation-for="IssueDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>
</div>










<div class="row">
    <div class="col-md-4">
      
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ITL_MakeId.Web/Views/Cards/CardRegistrationMenu.cshtml
@{
    Layout = "_CardLayout";
    ViewData["Title"] = "Registration";
}

<div class="col-md-6 mr-auto ml-auto p-0 mt-3 mb-5">

<h3 class="formbar mb-0">Registration</h3>
    <div class="col-md-12 form-bg text-center">
        <div class="pt-4 pb-2">
            <a class="text-capitalize font-weight-bold" asp-area="" asp-controller="Cards" asp-action="Create">Card Registration (Single Entry)</a>
        </div> 
        <div class="pb-4">
            <a class="text-capitalize font-weight-bold" asp-area="" asp-controller="Cards" asp-action="Excel">Card Registration (Bulk Entry)</a>
        </div>
    </div>
</div>

ITL_MakeId.Web/Views/Cards/Create.cshtml
@model ITL_MakeId.Model.ViewModel.IdentityCardViewModel

@{
    Layout = "_CardLayout";
    ViewData["Title"] = "Registration";
}

<link href="~/css/AutoComplete.css" rel="stylesheet" />

<div class="col-md-6 mr-auto ml-auto p-0 mt-3 mb-5">

    <h3 class="formbar mb-0">Registration</h3>
    <div class="col-md-12 form-bg">
        <form enctype="multipart/form-data" asp-action="Create" class="pb-5">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-12">
                @*<div class="col-md-8">
                    <div class="col-md-3">
                        <img src="~/image/noimage.jpg" class="upload-box border border-info" id="output" />
                    </div>
                </div>*@

                <div class="form-group col-md-6 float-left">
                    <div class="form-group">
                        <label asp-for="CardCategory" class="control-label"></label>
                        <select id="categoryId" asp-for="CardCategoryId" class="form-control" asp-items="ViewBag.CardCategories"> <option disabled selected>Select Category First</option></select>
                        <span asp-validation-for="CardCategory" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input id="nameId" asp-for="Name" class="form-control" placeholder="Enter your Name"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    @*<div class="form-group">
            <label asp-for="BloodGroup" class="control-label"></label>
            <select asp-for="BloodGroupId" class="form-control" asp-items="ViewBag.BloodGroupId"></select>
            <span asp-validation-for="BloodGroup" class="text-danger"></span>
        </div>*@

                    <div class="form-group">
                        <label asp-for="BloodGroup" class="control-label"></label>
                        <select id="bloodId" asp-for="BloodGroupId" class="form-control" asp-items="ViewBag.BloodGroups"><option disabled selected>Select Blood Group</option></select>
                        <span asp-validation-for="BloodGroup" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="control-label"> Date of Birth</label>
                        <input id="dobId" asp-for="DateOfBirth" class="form-control" />
                        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                    </div>


                    @*<div class="form-group">
                        <label asp-for="ImagePathOfUser" class="control-label"></label>
                        <div class="custom-file">
                            <input asp-for="ImagePathOfUser" class="form-control custom-file-input" onchange="loadFile(event)" />
                            <label class="custom-file-label">Choose Image...</label>
                            <span asp-validation-for="ImagePathOfUser" class="text-danger"></span>
                        </div>
                    </div>*@

                </div>
      

                <div class="form-group col-md-6 float-left">
                    <div class="form-group">
                        <label asp-for="Designation" class="control-label"></label>
                        <select id="desId" asp-for="DesignationId" class="form-control" asp-items="ViewBag.Designations"><option disabled selected>Select Designation</option></select>
                        <span asp-validation-for="Designation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CardNumber" class="control-label"></label>
                        <input id="cardNumberId" asp-for="CardNumber" class="form-control" readonly="readonly" />
                        <span asp-validation-for="CardNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Department" class="control-label"></label>
                        <select asp-for="Department" id="deptId" class="form-control" asp-items="ViewBag.Departments"></select>
                        <span asp-validation-for="Department" class="text-danger"></span>
                    </div>

                    @*<div class="form-group">
                        <label asp-for="Department" class="control-label"></label>
                        <input asp-for="Department" class="form-control"/>
                        <span asp-validation-for="Department" class="text-danger"></span>
                    </div>*@

                    @*<div class="form-group">
                        <label asp-for="Department" class="control-label"></label>
                        <input asp-for="Department" id="deptName" class="form-control autocomplete" />
                        <span asp-validation-for="Department" class="text-danger"></span>
                    </div>*@

                    @*<div class="form-group">
                        <label asp-for="ImagePathOfUserSignature" class="control-label"></label>
                        <div class="custom-file">
                            <input asp-for="ImagePathOfUserSignature" class="form-control custom-file-input" />
                            <label class="custom-file-label">Choose Signaure...</label>
                            <span asp-validation-for="ImagePathOfUserSignature" class="text-danger"></span>
                        </div>
                    </div>*@

                </div>
                <div class="form-group col-md-6 float-left">
                </div>
            </div>
            <div class="">
                <input type="submit" value="Create" class="btn btn-primary ml-5" />
                <a asp-action="Index" class="btn back-btn ml-5">Back to List</a>
            </div>

        </form>

    </div>
</div>
}


@section Scripts{

    @*<script src="~/js/uploadimage.js"></script>*@
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            $('#deptId').autocomplete({
                source: '/Cards/DepartmentSearch'
            });


            //if ($("#categoryId").val() != null) {
            //    var TextBox = document.getElementById(nameId);
            //    TextBox.disabled = true;

            //    //$("#nameId")();
            //    //$("#nameId").prop('disabled', true);
            //    //document.getElementById("nameId").disabled = true;
            //}

        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ITL_MakeId.Web/Views/Cards/Dashboard.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Dashboard";
}

@if (SignInManager.IsSignedIn(User))
{
    <div class="col-md-8 mr-auto ml-auto padding-dashboard mt-3 form-bg text-center">
        <h3 class="formbar mb-0">Dashboard</h3>

        <div class="card text-white bg-primary ml-5 mt-3 float-left" style="min-width: 14rem;">
            <div class="card-header">Request For Cards</div>
            <div class="card-body">
                <a class="text-white"asp-area="" asp-controller="Cards" asp-action="UserRequestForCard">
                    <h5 class="card-title">@ViewBag.RequestedIdentityCards</h5>
                </a>
            </div>
        </div>

        <div class="card text-white bg-success ml-5 mt-3 float-left" style="min-width: 14rem;">
            <div class="card-header">Validated Cards</div>
            <div class="card-body">
                <a class="text-white" asp-area="" asp-controller="Cards" asp-action="ValidatedUsers">  
                    <h5 class="card-title">@ViewBag.ValidatedIdentityCards</h5>
                    </a>
            </div>
        </div>

        <div class="card text-white bg-danger ml-5 mt-3 float-left" style="min-width: 14rem;">
            <div class="card-header">Expired Cards</div>
            <div class="card-body">
                <a class="text-white" asp-area="" asp-controller="Cards" asp-action="ExpiredUserCards"> <h5 class="card-title">@ViewBag.ExpiredIdentityCards</h5></a>
            </div>
        </div>
    </div>
}

else
{
<div class="text-center ml-auto mr-auto mt-3">
    <h1 class="display-4 mt-5 mb-5">Welcome</h1>
    <h3 class="display-4 mb-5">To</h3>
    <img class="mb-5 col-md-10" src="~/image/ba-2.png" />
</div>
}

ITL_MakeId.Web/Views/Cards/Delete.cshtml
@model ITL_MakeId.Model.DomainModel.IdentityCard

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IdentityCard</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Designation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Designation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BloodGroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BloodGroup)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CardNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CardNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePathOfUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePathOfUser)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePathOfUserSignature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePathOfUserSignature)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePathOfAuthorizedSignature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePathOfAuthorizedSignature)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyLogoPath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyLogoPath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CardInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CardInfo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ITL_MakeId.Web/Views/Cards/Excel.cshtml
@{
    Layout = "_CardLayout";
    ViewData["Title"] = "Bulk Entry";
}


<div class="col-md-6 mr-auto ml-auto p-0 mt-3 mb-5">
    <h3 class="formbar mb-0">Bulk Entry</h3>
    <div class="col-md-12 form-bg">

        @if (ViewBag.Message != null)
        {
            <p class="alert alert-success" id="successMessage">@ViewBag.Message!</p>
            <p class="alert alert-success" id="">Now, Click On "Give Card Number"!</p>
        }

        @if (ViewBag.Notes != null)
        {
    <p class="alert alert-success">@ViewBag.Notes</p>
        }

        <form asp-controller="Cards" asp-action="Excel" method="post" enctype="multipart/form-data" class="pt-3 mb-3">
            <input class="btn btn-info" type="file" class="" name="postedFile" />
            <input class="btn btn-success" type="submit" value="Import" />
        </form>



        <form asp-controller="Cards" asp-action="ProcessAfteBulkEntry" method="post" class="pt-3 pb-3">
            <h5 class="text-danger">After Each Bulk Entry Give Card Number to Uploaded Excel Sheet</h5>
            <input class="btn btn-info" type="submit" value="Give Card Number" />
        </form>
    </div>
</div>



@section Scripts{
    <script>
        $(function(){
            $('#successMessage').hide(2500);
        });
        $(function () {
            $('#info').hide(2500);
        });
    </script>
}